CREATE DATABASE DB_SISTEMA_PARQUEO
USE DB_SISTEMA_PARQUEO

CREATE TABLE NUEVO_LOGIN(
ID_NUEVO_LOGIN INT IDENTITY PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
CORREO VARCHAR(50) NOT NULL,
PASS VARCHAR(50) NOT NULL,
USUARIO VARCHAR(50) NOT NULL
)

CREATE TABLE ENCARGADO(
ID_ENCARGADO INT IDENTITY PRIMARY KEY,
NOMBRES VARCHAR(50) NOT NULL,
APELLIDOS VARCHAR(50) NOT NULL,
NUMERO_LICENCIA INT NOT NULL
)



CREATE TABLE VEHICULO(
ID_VEHICULO INT PRIMARY KEY  IDENTITY,
TIPO_VEHICULO VARCHAR(50) NOT NULL,
NUMERO_PLACA INT NOT NULL,
COLOR VARCHAR(50) NOT NULL

)
-----
CREATE TABLE FECHA_REGISTRO(
ID_FECHA_REGISTRO INT PRIMARY KEY IDENTITY,
FECHA DATETIME
)


CREATE TABLE TARIFA(
ID_TARIFA INT PRIMARY KEY IDENTITY,
CANTIDAD DECIMAL(6,2) NOT NULL,
ID_VEHICULO INT 

CONSTRAINT FK_TARIFA_VEHICULO FOREIGN KEY(ID_VEHICULO) REFERENCES VEHICULO(ID_VEHICULO) ON UPDATE CASCADE ON DELETE CASCADE
)


CREATE TABLE FLUJO_EFECTIVO(
ID_FLUJO_EFECTIVO INT PRIMARY KEY  IDENTITY,
CANTIDAD_VEHICULOS_INGRESADOS INT NOT NULL,
TOTAL_DINERO DECIMAL(6,2) NOT NULL,
 ID_FECHA_REGISTRO INT,

CONSTRAINT FK_FECHA_FLUJO FOREIGN KEY(ID_FECHA_REGISTRO) REFERENCES FECHA_REGISTRO(ID_FECHA_REGISTRO) ON UPDATE CASCADE ON DELETE CASCADE
)


CREATE TABLE DETALLE_ESTACIONAMIENTO(
ID_DETALLE_ESTACIONAMIENTO INT PRIMARY KEY IDENTITY,
HORA_ENTRADA varchar(50) NOT NULL,
CANTIDAD_HORAS INT NOT NULL,
ID_TARIFA INT ,
ID_FLUJO_EFECTIVO INT ,

CONSTRAINT FK_DETALLE_TARIFA FOREIGN KEY (ID_TARIFA) REFERENCES TARIFA(ID_TARIFA) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FK_FLUJO_EFECTIVO FOREIGN KEY (ID_FLUJO_EFECTIVO) REFERENCES FLUJO_EFECTIVO(ID_FLUJO_EFECTIVO) ON DELETE CASCADE ON UPDATE CASCADE
)


CREATE TABLE SESION(
ID_SESION INT PRIMARY KEY IDENTITY,
FECHA DATETIME NOT NULL,
ID_NUEVO_LOGIN INT ,

CONSTRAINT FK_SESION_LOGIN FOREIGN KEY(ID_NUEVO_LOGIN) REFERENCES NUEVO_LOGIN(ID_NUEVO_LOGIN) ON UPDATE CASCADE ON DELETE CASCADE
)


CREATE TABLE REGISTRAR_VEHICULO(
ID_REGISTRO INT PRIMARY KEY IDENTITY ,
ID_ENCARGADO INT,
ID_SESION INT ,
ID_DETALLE_ESTACIONAMIENTO INT ,
ID_VEHICULO INT ,

CONSTRAINT FK_REGISTRAR_ENCARGADO FOREIGN KEY(ID_ENCARGADO) REFERENCES ENCARGADO(ID_ENCARGADO) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FK_REGISTRAR_SESION FOREIGN KEY (ID_SESION) REFERENCES SESION(ID_SESION) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FK_REGISTRAR_DETALLE_ESTACIONAMIENTO FOREIGN KEY(ID_DETALLE_ESTACIONAMIENTO) REFERENCES DETALLE_ESTACIONAMIENTO(ID_DETALLE_ESTACIONAMIENTO) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FK_REGISTRAR_VEHICULO FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULO(ID_VEHICULO ) 
)

