

ALTER PROCEDURE [spOBTENERDATOS]
@PARAMETRO int
AS
BEGIN
	IF(EXISTS(SELECT NUMERO_PLACA FROM VEHICULO WHERE NUMERO_PLACA = @PARAMETRO))
	BEGIN
			SELECT NOMBRES,APELLIDOS, NUMERO_LICENCIA, NUMERO_PLACA, COLOR, TIPO_VEHICULO, HORA_ENTRADA, CANTIDAD_HORAS, CANTIDAD
			FROM REGISTRAR_VEHICULO RV INNER JOIN ENCARGADO E ON (RV.ID_ENCARGADO = E.ID_ENCARGADO) 
					       INNER JOIN VEHICULO V ON (RV.ID_VEHICULO = V.ID_VEHICULO)
						   INNER JOIN DETALLE_ESTACIONAMIENTO DE ON (RV.ID_DETALLE_ESTACIONAMIENTO = DE.ID_DETALLE_ESTACIONAMIENTO )
						   INNER JOIN TARIFA TF ON (TF.ID_TARIFA = DE.ID_TARIFA)
	END
	--ELSE
	--BEGIN
		--RETURN 'PLACA NO ENCONTRADA'
	--END
	--SELECT * FROM VEHICULO WHERE NUMERO_PLACA = @PARAMETRO
END
---------------------------------------------------------------------------------------

SELECT * FROM VEHICULO

EXEC spOBTENERDATOS 765432

SELECT * FROM VEHICULO
select NOMBRES,APELLIDOS,NUMERO_LICENCIA,TIPO_VEHICULO,COLOR from REGISTRAR_VEHICULO R, ENCARGADO E, VEHICULO V
WHERE R.ID_ENCARGADO = E.ID_ENCARGADO AND R.ID_VEHICULO = V.ID_VEHICULO



SELECT NOMBRES, COLOR FROM ENCARGADO E, VEHICULO V, REGISTRAR_VEHICULO R
WHERE R.ID_ENCARGADO = E.ID_ENCARGADO AND R.ID_VEHICULO = V.ID_VEHICULO

--select NOMBRES,APELLIDOS,NUMERO_LICENCIA,TIPO_VEHICULO,COLOR from REGISTRAR_VEHICULO R, ENCARGADO E, VEHICULO V
--INNER JOIN ENCARGADO ON( ID_REGISTRO = ID_ENCARGADO )
--WHERE R.ID_ENCARGADO = E.ID_ENCARGADO AND R.ID_VEHICULO = V.ID_VEHICULO
SELECT E.*, V.*
FROM ENCARGADO E, REGISTRAR_VEHICULO R, VEHICULO V
WHERE E.ID_ENCARGADO = R.ID_REGISTRO AND V.ID_VEHICULO = R.ID_REGISTRO 



SELECT CANTIDAD, TIPO_VEHICULO, NUMERO_PLACA
FROM VEHICULO V
INNER JOIN TARIFA T ON (V.ID_VEHICULO = T.ID_VEHICULO)

SELECT ID_REGISTRO, NOMBRES,APELLIDOS, NUMERO_LICENCIA, NUMERO_PLACA, COLOR, TIPO_VEHICULO, HORA_ENTRADA, CANTIDAD_HORAS, CANTIDAD
FROM REGISTRAR_VEHICULO RV INNER JOIN ENCARGADO E ON (RV.ID_ENCARGADO = E.ID_ENCARGADO) 
					       INNER JOIN VEHICULO V ON (RV.ID_VEHICULO = V.ID_VEHICULO)
						   INNER JOIN DETALLE_ESTACIONAMIENTO DE ON (RV.ID_DETALLE_ESTACIONAMIENTO = DE.ID_DETALLE_ESTACIONAMIENTO )
						   INNER JOIN TARIFA TF ON (TF.ID_TARIFA = DE.ID_TARIFA)
						  
--LAS RELACIONES SOLO SIGUEN UN CAMINO EN FORMA DE CADENA, UNA PUEDE PRESENTAR A LA OTRA, SIEMPRE Y CUANDO TENGAN ALGO EN COMUN

SELECT * FROM ENCARGADO