CREATE PROCEDURE [spEXPORTAR_DATOS]
@ID int
AS
BEGIN
	
	BEGIN
			SELECT ID_REGISTRO, NOMBRES,APELLIDOS, NUMERO_LICENCIA, NUMERO_PLACA, COLOR, TIPO_VEHICULO, HORA_ENTRADA, CANTIDAD_HORAS, CANTIDAD
			FROM REGISTRAR_VEHICULO RV INNER JOIN ENCARGADO E ON (RV.ID_ENCARGADO = E.ID_ENCARGADO) 
					       INNER JOIN VEHICULO V ON (RV.ID_VEHICULO = V.ID_VEHICULO)
						   INNER JOIN DETALLE_ESTACIONAMIENTO DE ON (RV.ID_DETALLE_ESTACIONAMIENTO = DE.ID_DETALLE_ESTACIONAMIENTO )
						   INNER JOIN TARIFA TF ON (TF.ID_TARIFA = DE.ID_TARIFA)
			WHERE ID_REGISTRO = @ID
	END
	

END

exec spEXPORTAR_DATOS 3--probablemente sea la condicion donde le dice que tiene que existir uno