CREATE PROCEDURE [spActualizar]
@ID INT,
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR(50),
@NUMERO_LICENCIA INT,
@NUMERO_PLACA INT,
@TIPO_VEHICULO VARCHAR(50),
@COLOR VARCHAR(50),
@HORA_ENTRADA varchar(10),
@HORAS_ESTACIONADO INT,
@TARIFA DECIMAL(6,2)
AS
BEGIN
	
	
	UPDATE ENCARGADO
	SET NOMBRES = @NOMBRE,
		APELLIDOS =@APELLIDO,
		NUMERO_LICENCIA = @NUMERO_LICENCIA 
	WHERE ID_ENCARGADO = @ID;
	

	UPDATE VEHICULO
	SET TIPO_VEHICULO = @TIPO_VEHICULO,
		NUMERO_PLACA = @NUMERO_PLACA,
		COLOR = @COLOR 
	WHERE ID_VEHICULO = @ID
	

	
	
	UPDATE  TARIFA
	SET CANTIDAD = @TARIFA
	WHERE ID_TARIFA = @ID
	 


	UPDATE  DETALLE_ESTACIONAMIENTO
	SET HORA_ENTRADA = @HORA_ENTRADA,
		CANTIDAD_HORAS = @HORAS_ESTACIONADO
	WHERE ID_DETALLE_ESTACIONAMIENTO = @ID
	
					
END
