ALTER PROCEDURE [spREGISTRO]
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR(50),
@NUMERO_LICENCIA INT,
@NUMERO_PLACA INT,
@TIPO_VEHICULO VARCHAR(50),
@COLOR VARCHAR(50),
@HORA_ENTRADA varchar(10),
@HORAS_ESTACIONADO INT,
@TARIFA DECIMAL(6,2)
AS
BEGIN
	
	DECLARE @CANTIDAD_VEHICULOS INT;
	DECLARE @TOTAL_DINERO DECIMAL(6,2) = 1;
	SELECT @CANTIDAD_VEHICULOS = IDENT_CURRENT('VEHICULO');

	--DECLARE @DINERO_TOTAL DECIMAL(6,2)  = SELECT SUM(TOTAL_DINERO) FROM FLUJO_EFECTIVO  ;
	--SELECT @DINERO_TOTAL 
	--DECLARE @DINERO_POR_VEHICULO =;
	SELECT @TOTAL_DINERO = @TARIFA * @HORAS_ESTACIONADO;
	--SELECT @IDENTIFICADOR = @IDENTIFICADOR + 1;
	
	INSERT INTO ENCARGADO(NOMBRES, APELLIDOS, NUMERO_LICENCIA) --VALUES ('EDENILSON','BATRES','12345');
	VALUES (@NOMBRE, @APELLIDO, @NUMERO_LICENCIA);

	INSERT INTO VEHICULO(TIPO_VEHICULO,NUMERO_PLACA, COLOR) --VALUES ('MERCEDES','12345', 'BLANCO');
	VALUES (@TIPO_VEHICULO,@NUMERO_PLACA, @COLOR);

	INSERT INTO FECHA_REGISTRO(FECHA) VALUES(GETDATE());

	DECLARE @FECHA_VAR INT = IDENT_CURRENT('FECHA_REGISTRO');
	INSERT INTO FLUJO_EFECTIVO(CANTIDAD_VEHICULOS_INGRESADOS, TOTAL_DINERO, ID_FECHA_REGISTRO) --VALUES(5, 10);
	VALUES(@CANTIDAD_VEHICULOS, @TOTAL_DINERO,@FECHA_VAR);

	--DECLARE @IDENTIFICADOR INT = IDENT_CURRENT('VEHICULO')+1;
	DECLARE @IDENTIFICADOR INT = IDENT_CURRENT('VEHICULO');
	--SET @IDENTIFICADOR = LAST_INSERT_ID(@IDENTIFICADOR + 1);

	INSERT INTO TARIFA(CANTIDAD, ID_VEHICULO)-- VALUES (2, 1)
	VALUES (@TARIFA, @IDENTIFICADOR)

	DECLARE @FLUJOVAR INT = IDENT_CURRENT('FLUJO_EFECTIVO');
	DECLARE @TARIFAVAR INT = IDENT_CURRENT('TARIFA');

	INSERT INTO DETALLE_ESTACIONAMIENTO(HORA_ENTRADA, CANTIDAD_HORAS,ID_TARIFA, ID_FLUJO_EFECTIVO) --VALUES ('9:00 AM', 3, 1, 1);
	VALUES (@HORA_ENTRADA, @HORAS_ESTACIONADO, @TARIFAVAR, @FLUJOVAR);

	--
	--INSERT INTO SESION VALUES (GETDATE(), 1)
	--

	DECLARE @ENCARGADO_VAR INT = IDENT_CURRENT('ENCARGADO');
	DECLARE @SESION_VAR INT = IDENT_CURRENT('SESION');
	DECLARE @DETALLE_VAR INT = IDENT_CURRENT('DETALLE_ESTACIONAMIENTO');
	DECLARE @VEHICULO_VAR INT = IDENT_CURRENT('VEHICULO');
	INSERT INTO REGISTRAR_VEHICULO(ID_ENCARGADO, ID_SESION, ID_DETALLE_ESTACIONAMIENTO, ID_VEHICULO) --VALUES(1,1, 1,1);
	VALUES(@ENCARGADO_VAR,@SESION_VAR, @DETALLE_VAR,@VEHICULO_VAR);

	
					
END




--select * from REGISTRAR_VEHICULO
--select * from DETALLE_ESTACIONAMIENTO

--sesion no esta reciviendo paramentros
--registrar vehiculo
