select * from VEHICULO
SELECT * FROM FLUJO_EFECTIVO
DELETE VEHICULO.* FROM VEHICULO
DELETE FROM TARIFA
DELETE FROM DETALLE_ESTACIONAMIENTO


DELETE FROM SESION WHERE ID_SESION = 3
SELECT * FROM VEHICULO
SELECT * FROM ENCARGADO
SELECT * FROM TARIFA
SELECT * FROM FLUJO_EFECTIVO
SELECT * FROM FECHA_REGISTRO
SELECT * FROM DETALLE_ESTACIONAMIENTO
SELECT * FROM SESION
SELECT * FROM REGISTRAR_VEHICULO


