--procedimiento almacenado de registro de vehiculos:

exec spREGISTRAR_VEHICULOS,,'9:00','5','10';

 
 --drop procedure spREGISTRAR_VEHICULOS

 EXEC spENCARGADO  'maria','cena','12345678'
CREATE PROCEDURE [spENCARGADO]
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR(50),
@NUMERO_LICENCIA INT


AS
BEGIN
	
	--INGRESANDO DATOS A TABLA ENCARGADO
	INSERT INTO ENCARGADO(NOMBRES, APELLIDOS, NUMERO_LICENCIA)
	VALUES (@NOMBRE, @APELLIDO, @NUMERO_LICENCIA);
	
END
SELECT * FROM VEHICULO;

---------------------------------------------------------
EXEC spVEHICULO '123','moto','VERDER'
ALTER PROCEDURE [spVEHICULO]
@NUMERO_PLACA INT,
@TIPO_VEHICULO VARCHAR(50),
@COLOR VARCHAR(50)
AS
BEGIN
	INSERT INTO VEHICULO(TIPO_VEHICULO,NUMERO_PLACA, COLOR)
	VALUES (@TIPO_VEHICULO,@NUMERO_PLACA, @COLOR);
	
END

SELECT * FROM VEHICULO

-------------------------------------------------------------

-------------------------------------------------------------
ALTER PROCEDURE [spDETALLES]

@HORA_ENTRADA varchar(10),
@HORAS_ESTACIONADO INT,
@TARIFA DECIMAL(6,2)
AS
BEGIN
	INSERT INTO TARIFA(CANTIDAD)
	VALUES (@TARIFA)
	INSERT INTO DETALLE_ESTACIONAMIENTO(HORA_ENTRADA, CANTIDAD_HORAS)
	VALUES (@HORA_ENTRADA, @HORAS_ESTACIONADO);
	
END

EXEC spDETALLES '9:00','2','12'

SELECT * FROM vehiculo