--vista sobre colsulta de datos
CREATE VIEW vVISUALIZAR_INFORMACION
AS
SELECT ID_REGISTRO, NOMBRES,APELLIDOS, NUMERO_LICENCIA, NUMERO_PLACA, COLOR, TIPO_VEHICULO, HORA_ENTRADA, CANTIDAD_HORAS, CANTIDAD
			FROM REGISTRAR_VEHICULO RV INNER JOIN ENCARGADO E ON (RV.ID_ENCARGADO = E.ID_ENCARGADO) 
					       INNER JOIN VEHICULO V ON (RV.ID_VEHICULO = V.ID_VEHICULO)
						   INNER JOIN DETALLE_ESTACIONAMIENTO DE ON (RV.ID_DETALLE_ESTACIONAMIENTO = DE.ID_DETALLE_ESTACIONAMIENTO )
						   INNER JOIN TARIFA TF ON (TF.ID_TARIFA = DE.ID_TARIFA)
			

SELECT * FROM vVISUALIZAR_INFORMACION
